### ISSUE TITLE
Spelling Mistake on Tile Size Randomization

### ISSUE THREAD

**Issue by mellymellymellymelly** [Jackaroo3007/Bugs-for-excel-spreadsheet#1]
![image](https://github.com/Jackaroo3007/Bugs-for-excel-spreadsheet/assets/146385566/7e9f94aa-504e-400e-b34f-86f3b37b3486)
There is a mispelling where it says _bag_ tile when it should say _big_ tile.
Line 51

**Comment by Jackaroo3007** [comment]
Please could you give further info, what line is this on?

**Comment by Jackaroo3007** [comment]
Okay, will get working on it :D

**Comment by Jackaroo3007** [comment]
Fixed, sorry for the inconvenience :)
