### ISSUE TITLE
False Signaller Tile Interactions

### ISSUE THREAD

**Issue by mellymellymellymelly** [Jackaroo3007/Bugs-for-excel-spreadsheet#2]
These two lines are not caused by the signaller tile, and should be moved under the Other Tile Interactions heading:
![image](https://github.com/Jackaroo3007/Bugs-for-excel-spreadsheet/assets/146385566/0b2dd41a-11f9-4815-b8c1-c97e822811fd)
Lines 44 and 45

**Comment by Jackaroo3007** [comment]
Will get working on it, sorry

**Comment by Jackaroo3007** [comment]
Fixed!
