### ISSUE TITLE
Signaller Tile Update

### ISSUE THREAD

**Issue by mellymellymellymelly** [Jackaroo3007/Bugs-for-excel-spreadsheet#3]
Line 43 is outdated, and has been updated recently.
Image for reference:
![image](https://github.com/Jackaroo3007/Bugs-for-excel-spreadsheet/assets/146385566/b1d2fa0c-4ea8-42ce-8082-e0a905df0073)

The one that mentions the propeller tile should be placed on a new line.

**Comment by Jackaroo3007** [comment]
Working on fixing it!

**Comment by Jackaroo3007** [comment]
Fixed!
